import pptxgen from "pptxgenjs"

const PALETTE = {
    primary: "2563EB",     // Royal Blue
    primaryDark: "1D4ED8",
    secondary: "0F172A",   // Slate 900
    cardBg: "F8FAFC",      // Slate 50
    cardBorder: "E2E8F0",  // Slate 200
    accent: "6366F1",      // Indigo
    accentLight: "EEF2FF",
    success: "10B981",     // Emerald
    successLight: "ECFDF5",
    textDark: "0F172A",
    textMuted: "64748B",
    white: "FFFFFF",
    gradientStart: "1E293B",
    gradientEnd: "0F172A"
}

export const generatePpt = async (data) => {
    const ppt = new pptxgen()
    ppt.layout = "LAYOUT_WIDE" // 13.33 x 7.5 inches
    ppt.author = "Nexora Platform"
    ppt.title = data.title || "Presentation"
    ppt.subject = data.subtitle || data.title
    ppt.company = "Nexora"
    ppt.theme = {
        headFontFace: "Arial",
        bodyFontFace: "Calibri"
    }

    // 1. Cover Slide
    addCover(ppt, data)

    // 2. Content Slides with layout discrimination
    const slides = data?.slides || []
    slides.forEach((s, idx) => {
        const slideType = s.type || detectSlideType(s)
        const page = idx + 1
        const total = slides.length

        switch (slideType) {
            case "comparison":
                addComparisonSlide(ppt, s, page, total)
                break
            case "process":
                addProcessSlide(ppt, s, page, total)
                break
            case "stats":
            case "metrics":
                addMetricsSlide(ppt, s, page, total)
                break
            case "architecture":
                addArchitectureSlide(ppt, s, page, total)
                break
            default:
                addConceptSlide(ppt, s, page, total)
                break
        }
    })

    // 3. Closing Slide
    addThankYou(ppt, data)

    return ppt
}

function detectSlideType(slide) {
    if (slide.comparison || (slide.leftTitle && slide.rightTitle)) return "comparison"
    if (slide.steps && slide.steps.length > 0) return "process"
    if (slide.metrics && slide.metrics.length > 0) return "stats"
    if (slide.components && slide.components.length > 0) return "architecture"
    return "concept"
}

// ==================== COVER SLIDE ====================
function addCover(ppt, data) {
    const slide = ppt.addSlide()
    slide.background = { color: PALETTE.secondary }

    // Top Accent Bar
    slide.addShape(ppt.ShapeType.rect, {
        x: 0,
        y: 0,
        w: 13.33,
        h: 0.25,
        fill: { color: PALETTE.primary },
        line: { color: PALETTE.primary }
    })

    // Badge
    slide.addShape(ppt.ShapeType.roundRect, {
        x: 1.0,
        y: 1.6,
        w: 2.2,
        h: 0.4,
        fill: { color: PALETTE.primary },
        line: { color: PALETTE.primary },
        radius: 0.08
    })
    slide.addText("PRESENTATION", {
        x: 1.0,
        y: 1.6,
        w: 2.2,
        h: 0.4,
        align: "center",
        color: PALETTE.white,
        bold: true,
        fontSize: 11,
        fontFace: "Arial"
    })

    // Main Title
    slide.addText(data.title || "Modern Presentation", {
        x: 1.0,
        y: 2.3,
        w: 11.33,
        h: 1.6,
        color: PALETTE.white,
        bold: true,
        fontSize: 32,
        fontFace: "Arial",
        fit: "shrink"
    })

    // Subtitle
    if (data.subtitle) {
        slide.addText(data.subtitle, {
            x: 1.0,
            y: 4.1,
            w: 11.33,
            h: 0.8,
            color: "94A3B8",
            fontSize: 16,
            fontFace: "Calibri",
            fit: "shrink"
        })
    }

    // Divider Line
    slide.addShape(ppt.ShapeType.line, {
        x: 1.0,
        y: 5.2,
        w: 4.0,
        h: 0,
        line: { color: PALETTE.primary, width: 2 }
    })

    // Footer
    slide.addText("Generated by Nexora Platform", {
        x: 1.0,
        y: 6.7,
        w: 8.0,
        h: 0.3,
        color: "64748B",
        fontSize: 10,
        fontFace: "Calibri"
    })
}

// Base header & footer on content slides
function setupSlideHeaderFooter(slide, ppt, title, category, page, total) {
    slide.background = { color: PALETTE.white }

    // Category / Tagline
    if (category) {
        slide.addText(category.toUpperCase(), {
            x: 0.8,
            y: 0.35,
            w: 10.0,
            h: 0.25,
            fontSize: 10,
            bold: true,
            color: PALETTE.primary,
            fontFace: "Arial"
        })
    }

    // Slide Title
    slide.addText(title, {
        x: 0.8,
        y: category ? 0.6 : 0.4,
        w: 11.7,
        h: 0.55,
        fontSize: 22,
        bold: true,
        color: PALETTE.secondary,
        fontFace: "Arial"
    })

    // Top subtle divider
    slide.addShape(ppt.ShapeType.line, {
        x: 0.8,
        y: 1.25,
        w: 11.7,
        h: 0,
        line: { color: PALETTE.cardBorder, width: 1.0 }
    })

    // Footer
    slide.addText("Nexora Platform", {
        x: 0.8,
        y: 6.9,
        w: 4.0,
        h: 0.3,
        fontSize: 9,
        color: PALETTE.textMuted,
        fontFace: "Calibri"
    })

    slide.addText(`${page} / ${total}`, {
        x: 11.0,
        y: 6.9,
        w: 1.5,
        h: 0.3,
        align: "right",
        fontSize: 9,
        bold: true,
        color: PALETTE.textMuted,
        fontFace: "Calibri"
    })
}

// ==================== CONCEPT / STANDARD SLIDE ====================
function addConceptSlide(ppt, slideData, page, total) {
    const slide = ppt.addSlide()
    setupSlideHeaderFooter(slide, ppt, slideData.title, slideData.tagline || slideData.category, page, total)

    const points = slideData.points || []
    const totalPoints = Math.min(points.length, 5)

    points.slice(0, totalPoints).forEach((point, i) => {
        const y = 1.5 + (i * 0.95)

        // Card Container
        slide.addShape(ppt.ShapeType.roundRect, {
            x: 0.8,
            y,
            w: 11.7,
            h: 0.8,
            fill: { color: i === 0 ? "F0F7FF" : PALETTE.cardBg },
            line: { color: i === 0 ? "BFDBFE" : PALETTE.cardBorder, width: 1 },
            radius: 0.08
        })

        // Number Badge
        slide.addShape(ppt.ShapeType.ellipse, {
            x: 1.05,
            y: y + 0.22,
            w: 0.35,
            h: 0.35,
            fill: { color: i === 0 ? PALETTE.primary : "E2E8F0" },
            line: { color: i === 0 ? PALETTE.primary : "CBD5E1" }
        })
        slide.addText(`${i + 1}`, {
            x: 1.05,
            y: y + 0.22,
            w: 0.35,
            h: 0.35,
            align: "center",
            valign: "middle",
            fontSize: 11,
            bold: true,
            color: i === 0 ? PALETTE.white : PALETTE.secondary,
            fontFace: "Arial"
        })

        // Text
        slide.addText(point, {
            x: 1.55,
            y: y + 0.12,
            w: 10.7,
            h: 0.55,
            fontSize: 14,
            color: PALETTE.textDark,
            fontFace: "Calibri",
            valign: "middle",
            fit: "shrink"
        })
    })

    // Takeaway callout if present
    if (slideData.keyTakeaway) {
        slide.addShape(ppt.ShapeType.roundRect, {
            x: 0.8,
            y: 6.25,
            w: 11.7,
            h: 0.55,
            fill: { color: "FEF3C7" },
            line: { color: "FDE68A" },
            radius: 0.06
        })
        slide.addText(`💡 Key Takeaway: ${slideData.keyTakeaway}`, {
            x: 1.0,
            y: 6.25,
            w: 11.3,
            h: 0.55,
            fontSize: 11,
            bold: true,
            color: "92400E",
            fontFace: "Calibri",
            valign: "middle",
            fit: "shrink"
        })
    }
}

// ==================== COMPARISON SLIDE ====================
function addComparisonSlide(ppt, slideData, page, total) {
    const slide = ppt.addSlide()
    setupSlideHeaderFooter(slide, ppt, slideData.title, slideData.tagline || "Side-by-Side Comparison", page, total)

    const comp = slideData.comparison || {}
    const leftTitle = comp.leftTitle || slideData.leftTitle || "Option A"
    const leftPoints = comp.leftPoints || slideData.leftPoints || []
    const rightTitle = comp.rightTitle || slideData.rightTitle || "Option B"
    const rightPoints = comp.rightPoints || slideData.rightPoints || []

    // Left Column Box
    slide.addShape(ppt.ShapeType.roundRect, {
        x: 0.8,
        y: 1.5,
        w: 5.6,
        h: 5.0,
        fill: { color: "F8FAFC" },
        line: { color: "CBD5E1", width: 1.5 },
        radius: 0.1
    })
    // Left Header
    slide.addShape(ppt.ShapeType.roundRect, {
        x: 0.8,
        y: 1.5,
        w: 5.6,
        h: 0.7,
        fill: { color: "3B82F6" },
        line: { color: "3B82F6" },
        radius: 0.1
    })
    slide.addText(leftTitle, {
        x: 1.0,
        y: 1.5,
        w: 5.2,
        h: 0.7,
        fontSize: 16,
        bold: true,
        color: PALETTE.white,
        align: "center",
        valign: "middle"
    })
    // Left Points
    leftPoints.slice(0, 5).forEach((pt, i) => {
        const y = 2.4 + (i * 0.75)
        slide.addShape(ppt.ShapeType.ellipse, {
            x: 1.1,
            y: y + 0.1,
            w: 0.12,
            h: 0.12,
            fill: { color: "3B82F6" }
        })
        slide.addText(pt, {
            x: 1.35,
            y,
            w: 4.8,
            h: 0.6,
            fontSize: 13,
            color: PALETTE.textDark,
            fit: "shrink"
        })
    })

    // Right Column Box
    slide.addShape(ppt.ShapeType.roundRect, {
        x: 6.9,
        y: 1.5,
        w: 5.6,
        h: 5.0,
        fill: { color: "F8FAFC" },
        line: { color: "CBD5E1", width: 1.5 },
        radius: 0.1
    })
    // Right Header
    slide.addShape(ppt.ShapeType.roundRect, {
        x: 6.9,
        y: 1.5,
        w: 5.6,
        h: 0.7,
        fill: { color: "10B981" },
        line: { color: "10B981" },
        radius: 0.1
    })
    slide.addText(rightTitle, {
        x: 7.1,
        y: 1.5,
        w: 5.2,
        h: 0.7,
        fontSize: 16,
        bold: true,
        color: PALETTE.white,
        align: "center",
        valign: "middle"
    })
    // Right Points
    rightPoints.slice(0, 5).forEach((pt, i) => {
        const y = 2.4 + (i * 0.75)
        slide.addShape(ppt.ShapeType.ellipse, {
            x: 7.2,
            y: y + 0.1,
            w: 0.12,
            h: 0.12,
            fill: { color: "10B981" }
        })
        slide.addText(pt, {
            x: 7.45,
            y,
            w: 4.8,
            h: 0.6,
            fontSize: 13,
            color: PALETTE.textDark,
            fit: "shrink"
        })
    })
}

// ==================== PROCESS / ROADMAP SLIDE ====================
function addProcessSlide(ppt, slideData, page, total) {
    const slide = ppt.addSlide()
    setupSlideHeaderFooter(slide, ppt, slideData.title, slideData.tagline || "Step-by-Step Workflow", page, total)

    const steps = slideData.steps || []
    const totalSteps = Math.min(steps.length, 4)
    const cardWidth = (11.7 - (totalSteps - 1) * 0.3) / totalSteps

    steps.slice(0, totalSteps).forEach((st, i) => {
        const x = 0.8 + i * (cardWidth + 0.3)

        // Step Card
        slide.addShape(ppt.ShapeType.roundRect, {
            x,
            y: 1.8,
            w: cardWidth,
            h: 4.6,
            fill: { color: PALETTE.cardBg },
            line: { color: PALETTE.cardBorder, width: 1.5 },
            radius: 0.1
        })

        // Step Number Badge
        slide.addShape(ppt.ShapeType.roundRect, {
            x: x + (cardWidth - 0.8) / 2,
            y: 2.1,
            w: 0.8,
            h: 0.8,
            fill: { color: PALETTE.primary },
            line: { color: PALETTE.primary },
            radius: 0.15
        })
        slide.addText(`${st.step || i + 1}`, {
            x: x + (cardWidth - 0.8) / 2,
            y: 2.1,
            w: 0.8,
            h: 0.8,
            align: "center",
            valign: "middle",
            fontSize: 18,
            bold: true,
            color: PALETTE.white
        })

        // Step Title
        slide.addText(st.title || `Phase ${i + 1}`, {
            x: x + 0.15,
            y: 3.1,
            w: cardWidth - 0.3,
            h: 0.6,
            align: "center",
            fontSize: 14,
            bold: true,
            color: PALETTE.secondary,
            fit: "shrink"
        })

        // Step Description
        slide.addText(st.description || st.text || "", {
            x: x + 0.2,
            y: 3.8,
            w: cardWidth - 0.4,
            h: 2.3,
            align: "center",
            fontSize: 12,
            color: PALETTE.textDark,
            fit: "shrink"
        })
    })
}

// ==================== METRICS / STATS SLIDE ====================
function addMetricsSlide(ppt, slideData, page, total) {
    const slide = ppt.addSlide()
    setupSlideHeaderFooter(slide, ppt, slideData.title, slideData.tagline || "Key Metrics & Impact", page, total)

    const metrics = slideData.metrics || []
    const totalMetrics = Math.min(metrics.length, 3)
    const cardWidth = (11.7 - (totalMetrics - 1) * 0.4) / totalMetrics

    metrics.slice(0, totalMetrics).forEach((m, i) => {
        const x = 0.8 + i * (cardWidth + 0.4)

        // Stat Card
        slide.addShape(ppt.ShapeType.roundRect, {
            x,
            y: 1.8,
            w: cardWidth,
            h: 3.2,
            fill: { color: i === 1 ? "EEF2FF" : PALETTE.cardBg },
            line: { color: i === 1 ? "C7D2FE" : PALETTE.cardBorder, width: 1.5 },
            radius: 0.12
        })

        // Big Metric Number
        slide.addText(m.value || "100%", {
            x: x + 0.2,
            y: 2.2,
            w: cardWidth - 0.4,
            h: 1.0,
            align: "center",
            fontSize: 34,
            bold: true,
            color: i === 1 ? PALETTE.accent : PALETTE.primary,
            fit: "shrink"
        })

        // Metric Label
        slide.addText(m.label || "Key Metric", {
            x: x + 0.2,
            y: 3.4,
            w: cardWidth - 0.4,
            h: 0.8,
            align: "center",
            fontSize: 13,
            bold: true,
            color: PALETTE.textDark,
            fit: "shrink"
        })
    })

    // Bottom Summary Card
    if (slideData.summary || slideData.points?.length) {
        const summaryText = slideData.summary || slideData.points?.join(" • ")
        slide.addShape(ppt.ShapeType.roundRect, {
            x: 0.8,
            y: 5.3,
            w: 11.7,
            h: 1.3,
            fill: { color: "F1F5F9" },
            line: { color: "CBD5E1" },
            radius: 0.08
        })
        slide.addText(summaryText, {
            x: 1.1,
            y: 5.4,
            w: 11.1,
            h: 1.1,
            fontSize: 13,
            color: PALETTE.textDark,
            valign: "middle",
            fit: "shrink"
        })
    }
}

// ==================== ARCHITECTURE / COMPONENTS SLIDE ====================
function addArchitectureSlide(ppt, slideData, page, total) {
    const slide = ppt.addSlide()
    setupSlideHeaderFooter(slide, ppt, slideData.title, slideData.tagline || "System Architecture", page, total)

    const comps = slideData.components || []
    const totalComps = Math.min(comps.length, 4)
    const cardWidth = (11.7 - (totalComps - 1) * 0.3) / totalComps

    comps.slice(0, totalComps).forEach((c, i) => {
        const x = 0.8 + i * (cardWidth + 0.3)

        slide.addShape(ppt.ShapeType.roundRect, {
            x,
            y: 1.8,
            w: cardWidth,
            h: 3.6,
            fill: { color: PALETTE.cardBg },
            line: { color: PALETTE.cardBorder, width: 1.2 },
            radius: 0.1
        })

        slide.addShape(ppt.ShapeType.rect, {
            x: x + 0.2,
            y: 2.1,
            w: cardWidth - 0.4,
            h: 0.4,
            fill: { color: PALETTE.primaryDark },
            line: { color: PALETTE.primaryDark }
        })
        slide.addText(c.name || `Layer ${i + 1}`, {
            x: x + 0.2,
            y: 2.1,
            w: cardWidth - 0.4,
            h: 0.4,
            align: "center",
            valign: "middle",
            fontSize: 12,
            bold: true,
            color: PALETTE.white
        })

        slide.addText(c.role || c.description || "", {
            x: x + 0.2,
            y: 2.7,
            w: cardWidth - 0.4,
            h: 2.4,
            align: "center",
            fontSize: 12,
            color: PALETTE.textDark,
            fit: "shrink"
        })
    })

    if (slideData.flowSummary) {
        slide.addText(`Flow: ${slideData.flowSummary}`, {
            x: 0.8,
            y: 5.7,
            w: 11.7,
            h: 0.8,
            fontSize: 12,
            italic: true,
            color: PALETTE.textMuted,
            align: "center"
        })
    }
}

// ==================== CLOSING SLIDE ====================
function addThankYou(ppt, data) {
    const slide = ppt.addSlide()
    slide.background = { color: PALETTE.secondary }

    slide.addText("Thank You", {
        x: 0,
        y: 2.3,
        w: 13.33,
        h: 1.0,
        align: "center",
        color: PALETTE.white,
        fontSize: 38,
        bold: true,
        fontFace: "Arial"
    })

    slide.addText(data.title ? `Questions & Discussion on ${data.title}` : "Questions & Discussion", {
        x: 1.0,
        y: 3.5,
        w: 11.33,
        h: 0.6,
        align: "center",
        color: "94A3B8",
        fontSize: 16,
        fontFace: "Calibri"
    })

    slide.addText("Generated by Nexora Platform", {
        x: 0,
        y: 6.7,
        w: 13.33,
        h: 0.3,
        align: "center",
        color: "64748B",
        fontSize: 10,
        fontFace: "Calibri"
    })
}
